<?php

namespace App\Benzina;

trait ProjectsPumpTrait
{
    private const PROJECT_DESC_TITLES = [
        'es' => [
            'about' => 'Descripción del proyecto. Características, fortalezas y diferenciales.',
            'motivation' => 'Motivación y a quién va dirigido el proyecto.',
            'related' => 'Experiencia previa y equipo.',
        ],
        'gl' => [
            'about' => 'Características básicas.',
            'motivation' => 'Motivación e a quen vai dirixido o proxecto.',
            'related' => 'Experiencia previa e equipo.',
        ],
        'eu' => [
            'about' => 'Oinarrizko ezaugarriak eta helburuak.',
            'motivation' => 'Zerk bultzatzen zaitu eta zeini zuzenduta dago proiektua.',
            'related' => 'Proiektuaren deskribapenean derrigorrekoa da azaltzea kontutan hartzen den taldearen esperientzia.',
        ],
        'ca' => [
            'about' => 'Característiques bàsiques i objectius.',
            'motivation' => 'Motivació i a qui va dirigit el projecte.',
            'related' => 'Experiència prèvia i equip.',
        ],
        'en' => [
            'about' => 'Main features and goals of the crowdfunding campaign.',
            'motivation' => 'Why this is important.',
            'related' => 'Team and experience.',
        ],
        'fr' => [
            'about' => 'Caractéristiques principales.',
            'motivation' => 'Pourquoi est-ce important.',
            'related' => 'Expérience antérieure et équipe.',
        ],
        'it' => [
            'about' => 'Caratteristiche fondamentali.',
            'motivation' => 'Obiettivo e a chi si dirige il progetto.',
            'related' => 'Esperienza e team.',
        ],
        'de' => [
            'about' => 'Hauptmerkmale.',
            'motivation' => 'Warum das wichtig ist.',
            'related' => 'Team und Erfahrung.',
        ],
    ];

    private const PROJECT_KEYS = [
        'id',
        'name',
        'subtitle',
        'lang',
        'currency',
        'currency_rate',
        'status',
        'translate',
        'progress',
        'owner',
        'node',
        'amount',
        'mincost',
        'maxcost',
        'days',
        'num_investors',
        'popularity',
        'num_messengers',
        'num_posts',
        'created',
        'updated',
        'published',
        'success',
        'closed',
        'passed',
        'contract_name',
        'contract_nif',
        'phone',
        'contract_email',
        'address',
        'zipcode',
        'location',
        'country',
        'image',
        'description',
        'motivation',
        'video',
        'video_usubs',
        'about',
        'goal',
        'related',
        'spread',
        'reward',
        'category',
        'keywords',
        'media',
        'media_usubs',
        'currently',
        'project_location',
        'scope',
        'resource',
        'comment',
        'contract_entity',
        'contract_birthdate',
        'entity_office',
        'entity_name',
        'entity_cif',
        'post_address',
        'secondary_address',
        'post_zipcode',
        'post_location',
        'post_country',
        'amount_users',
        'amount_call',
        'maxproj',
        'analytics_id',
        'facebook_pixel',
        'social_commitment',
        'social_commitment_description',
        'execution_plan',
        'sustainability_model',
        'execution_plan_url',
        'sustainability_model_url',
        'sign_url',
        'sign_url_action',
    ];
}
