name: PHP CS Fixer

on: [pull_request]

env:
  PHP_VERSION: '8.3'
  PHP_EXTENSIONS: pdo_mysql

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    env:
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      DOCTRINE_ENCRYPTION_ENCRYPT_KEY: "0Y3McEg51558fcreunKodhuP+Ua/Yf+tp43GxmBVY4Q="
      DOCTRINE_ENCRYPTION_BLIND_INDEX_KEY: "cRt6Hf/3nEVG8XTBnZrOFCnOHJQ7PIE910EYIT+79EQ="

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_extensions: ${{ env.PHP_EXTENSIONS }}

      - name: PHP CS Fixer
        run: php ./vendor/bin/php-cs-fixer check
