name: PHPUnit

on: [push]

env:
  PHP_VERSION: '8.3'
  PHP_EXTENSIONS: pdo_mysql intl

jobs:
  phpunit:
    runs-on: ubuntu-latest

    env:
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      DOCTRINE_ENCRYPTION_ENCRYPT_KEY: "0Y3McEg51558fcreunKodhuP+Ua/Yf+tp43GxmBVY4Q="
      DOCTRINE_ENCRYPTION_BLIND_INDEX_KEY: "cRt6Hf/3nEVG8XTBnZrOFCnOHJQ7PIE910EYIT+79EQ="

    services:
      mariadb:
        image: mariadb:10.11.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: goteo
          MYSQL_DATABASE: goteo
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_extensions: ${{ env.PHP_EXTENSIONS }}

      - name: PHP diagnostics
        run: |
          php -v
          php --ini
          php -r 'echo "PHP_VERSION=", PHP_VERSION, PHP_EOL;'

      - name: PHPUnit
        run: php -d memory_limit=128M bin/phpunit -c phpunit.xml.dist
        env:
          DATABASE_URL: mysql://root:goteo@127.0.0.1:${{ job.services.mariadb.ports['3306'] }}/goteo
